Repository openshift-assisted/bugmaster-configurations, pull requests merged in 2023-06, with the labels that each got.

#8 MGMT-15031: Assign MCE, MetalLB and OCI jobs
  OWNERS
  OWNERS_ALIASES
  config/channel/assisted-deployment-ci/bug_master_configuration.yaml
Labels: lgtm, size/M, jira/valid-reference

#9 Add ncarboni as owner of remove node ZTP job
  config/channel/assisted-deployment-ci/bug_master_configuration.yaml
Labels: lgtm, size/XS, approved

#10 NO-ISSUE: Assign CAPI jobs to Crystal
  config/channel/assisted-deployment-ci/bug_master_configuration.yaml
Labels: size/S, lgtm, approved, jira/valid-reference
